<?php
/**
* @package shorty-tracking an ownCloud url shortener plugin addition
* @category internet
* @author Christian Reiner
* @copyright 2012-2012 Christian Reiner <foss@christian-reiner.info>
* @license GNU Affero General Public license (AGPL)
* @link information 
* @link repository https://svn.christian-reiner.info/svn/app/oc/shorty-tracking
*
* This library is free software; you can redistribute it and/or
* modify it under the terms of the GNU AFFERO GENERAL PUBLIC LICENSE
* License as published by the Free Software Foundation; either
* version 3 of the license, or any later version.
*
* This library is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU AFFERO GENERAL PUBLIC LICENSE for more details.
*
* You should have received a copy of the GNU Affero General Public
* License along with this library.
* If not, see <http://www.gnu.org/licenses/>.
*
*/

/**
 * @file ajax/list.php
 * @brief Ajax method to retrieve a list of clicks to a Shorty
 * @returns (json) success/error state indicator
 * @returns (number) Total number of shortys in the list
 * @returns (json) Numeric array of all shortys, associative array of attributes as values for every single shorty contained
 * @author Christian Reiner
 */

// swallow any accidential output generated by php notices and stuff to preserve a clean JSON reply structure
OC_Shorty_Tools::ob_control ( TRUE );

//no apps or filesystem
$RUNTIME_NOSETUPFS = TRUE;

// Check if we are a user
OCP\JSON::checkLoggedIn ( );
OCP\JSON::checkAppEnabled ( 'shorty' );
OCP\JSON::checkAppEnabled ( 'shorty-tracking' );

try
{
//   define ('PAGE_SIZE', 100);
//   $p_offset = OC_Shorty_Type::req_argument ( 'page', OC_Shorty_Type::INTEGER, FALSE) * PAGE_SIZE;
  $p_id      = OC_Shorty_Type::req_argument ( 'id',      OC_Shorty_Type::ID,     TRUE );
  // pre-sort list according to user preferences
  $p_sort = OC_ShortyTracking_Type::$SORTING[OCP\Config::getUserValue(OCP\User::getUser(),'shorty-tracking','list-sort-code','td')];
  $param = array
  (
    ':id  '   => $p_id,
    ':sort'   => $p_sort,
//     ':offset' => $p_offset,
//     ':limit'  => PAGE_SIZE,
  );
  $query = OCP\DB::prepare ( OC_ShortyTracking_Query::CLICK_LIST );
  $result = $query->execute($param);
  $reply = $result->fetchAll();

  // swallow any accidential output generated by php notices and stuff to preserve a clean JSON reply structure
  OC_Shorty_Tools::ob_control ( FALSE );
  OCP\Util::writeLog( 'shorty', sprintf("Prepared list of clicks holding %s entries.",sizeof($reply)), OC_Log::DEBUG );
  OCP\JSON::success ( array ( 'data'    => $reply,
                              'count'   => sizeof($reply),
                              'message' => OC_ShortyTracking_L10n::t('Number of entries: %s', count($reply)) ) );
} catch ( Exception $e ) { OC_Shorty_Exception::JSONerror($e); }
?>
